/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as TutorWalletRouteImport } from './routes/tutor.wallet'
import { Route as TutorToolsRouteImport } from './routes/tutor.tools'
import { Route as TutorStudentsRouteImport } from './routes/tutor.students'
import { Route as TutorSettingsRouteImport } from './routes/tutor.settings'
import { Route as TutorSessionsRouteImport } from './routes/tutor.sessions'
import { Route as TutorReviewsRouteImport } from './routes/tutor.reviews'
import { Route as TutorResourcesRouteImport } from './routes/tutor.resources'
import { Route as TutorProfileRouteImport } from './routes/tutor.profile'
import { Route as TutorNotificationsRouteImport } from './routes/tutor.notifications'
import { Route as TutorMessagesRouteImport } from './routes/tutor.messages'
import { Route as TutorGrowthRouteImport } from './routes/tutor.growth'
import { Route as TutorGetListedRouteImport } from './routes/tutor.get-listed'
import { Route as TutorEarningsRouteImport } from './routes/tutor.earnings'
import { Route as TutorCalendarRouteImport } from './routes/tutor.calendar'
import { Route as TutorAvailabilityRouteImport } from './routes/tutor.availability'
import { Route as TutorAnalyticsRouteImport } from './routes/tutor.analytics'
import { Route as StudentToolsRouteImport } from './routes/student.tools'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentBookingsRouteImport } from './routes/student.bookings'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentBillingRouteImport } from './routes/parent.billing'
import { Route as ClassesManageRouteImport } from './routes/classes.manage'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as TutorLessonsIndexRouteImport } from './routes/tutor.lessons.index'
import { Route as StudentTutorsIndexRouteImport } from './routes/student.tutors.index'
import { Route as StudentLessonsIndexRouteImport } from './routes/student.lessons.index'
import { Route as StudentClassesIndexRouteImport } from './routes/student.classes.index'
import { Route as ParentClassesIndexRouteImport } from './routes/parent.classes.index'
import { Route as ParentChildrenIndexRouteImport } from './routes/parent.children.index'
import { Route as TutorStudentsIdRouteImport } from './routes/tutor.students.$id'
import { Route as TutorLessonsNewRouteImport } from './routes/tutor.lessons.new'
import { Route as TutorLessonsIdRouteImport } from './routes/tutor.lessons.$id'
import { Route as StudentTutorsIdRouteImport } from './routes/student.tutors.$id'
import { Route as StudentLessonsIdRouteImport } from './routes/student.lessons.$id'
import { Route as StudentClassesIdRouteImport } from './routes/student.classes.$id'
import { Route as ParentClassesIdRouteImport } from './routes/parent.classes.$id'
import { Route as ParentChildrenChildIdRouteImport } from './routes/parent.children.$childId'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorWalletRoute = TutorWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => TutorRoute,
} as any)
const TutorToolsRoute = TutorToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => TutorRoute,
} as any)
const TutorStudentsRoute = TutorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TutorRoute,
} as any)
const TutorSettingsRoute = TutorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TutorRoute,
} as any)
const TutorSessionsRoute = TutorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TutorRoute,
} as any)
const TutorReviewsRoute = TutorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TutorRoute,
} as any)
const TutorResourcesRoute = TutorResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TutorRoute,
} as any)
const TutorProfileRoute = TutorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TutorRoute,
} as any)
const TutorNotificationsRoute = TutorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TutorRoute,
} as any)
const TutorMessagesRoute = TutorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TutorRoute,
} as any)
const TutorGrowthRoute = TutorGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => TutorRoute,
} as any)
const TutorGetListedRoute = TutorGetListedRouteImport.update({
  id: '/get-listed',
  path: '/get-listed',
  getParentRoute: () => TutorRoute,
} as any)
const TutorEarningsRoute = TutorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TutorRoute,
} as any)
const TutorCalendarRoute = TutorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAvailabilityRoute = TutorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAnalyticsRoute = TutorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TutorRoute,
} as any)
const StudentToolsRoute = StudentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBookingsRoute = StudentBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StudentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentBillingRoute = ParentBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ParentRoute,
} as any)
const ClassesManageRoute = ClassesManageRouteImport.update({
  id: '/classes/manage',
  path: '/classes/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorLessonsIndexRoute = TutorLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => TutorRoute,
} as any)
const StudentTutorsIndexRoute = StudentTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsIndexRoute = StudentLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClassesIndexRoute = StudentClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentClassesIndexRoute = ParentClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenIndexRoute = ParentChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => ParentRoute,
} as any)
const TutorStudentsIdRoute = TutorStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TutorStudentsRoute,
} as any)
const TutorLessonsNewRoute = TutorLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => TutorRoute,
} as any)
const TutorLessonsIdRoute = TutorLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => TutorRoute,
} as any)
const StudentTutorsIdRoute = StudentTutorsIdRouteImport.update({
  id: '/tutors/$id',
  path: '/tutors/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsIdRoute = StudentLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClassesIdRoute = StudentClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => StudentRoute,
} as any)
const ParentClassesIdRoute = ParentClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenChildIdRoute = ParentChildrenChildIdRouteImport.update({
  id: '/children/$childId',
  path: '/children/$childId',
  getParentRoute: () => ParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/tutor': typeof TutorRouteWithChildren
  '/admin/moderation': typeof AdminModerationRoute
  '/classes/$id': typeof ClassesIdRoute
  '/classes/manage': typeof ClassesManageRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/tools': typeof StudentToolsRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/availability': typeof TutorAvailabilityRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/get-listed': typeof TutorGetListedRoute
  '/tutor/growth': typeof TutorGrowthRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/profile': typeof TutorProfileRoute
  '/tutor/resources': typeof TutorResourcesRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRouteWithChildren
  '/tutor/tools': typeof TutorToolsRoute
  '/tutor/wallet': typeof TutorWalletRoute
  '/classes/': typeof ClassesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/parent/children/$childId': typeof ParentChildrenChildIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/student/classes/$id': typeof StudentClassesIdRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/tutor/lessons/$id': typeof TutorLessonsIdRoute
  '/tutor/lessons/new': typeof TutorLessonsNewRoute
  '/tutor/students/$id': typeof TutorStudentsIdRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/classes/': typeof ParentClassesIndexRoute
  '/student/classes/': typeof StudentClassesIndexRoute
  '/student/lessons/': typeof StudentLessonsIndexRoute
  '/student/tutors/': typeof StudentTutorsIndexRoute
  '/tutor/lessons/': typeof TutorLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/classes/$id': typeof ClassesIdRoute
  '/classes/manage': typeof ClassesManageRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/tools': typeof StudentToolsRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/availability': typeof TutorAvailabilityRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/get-listed': typeof TutorGetListedRoute
  '/tutor/growth': typeof TutorGrowthRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/profile': typeof TutorProfileRoute
  '/tutor/resources': typeof TutorResourcesRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRouteWithChildren
  '/tutor/tools': typeof TutorToolsRoute
  '/tutor/wallet': typeof TutorWalletRoute
  '/classes': typeof ClassesIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/parent/children/$childId': typeof ParentChildrenChildIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/student/classes/$id': typeof StudentClassesIdRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/tutor/lessons/$id': typeof TutorLessonsIdRoute
  '/tutor/lessons/new': typeof TutorLessonsNewRoute
  '/tutor/students/$id': typeof TutorStudentsIdRoute
  '/parent/children': typeof ParentChildrenIndexRoute
  '/parent/classes': typeof ParentClassesIndexRoute
  '/student/classes': typeof StudentClassesIndexRoute
  '/student/lessons': typeof StudentLessonsIndexRoute
  '/student/tutors': typeof StudentTutorsIndexRoute
  '/tutor/lessons': typeof TutorLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/tutor': typeof TutorRouteWithChildren
  '/admin/moderation': typeof AdminModerationRoute
  '/classes/$id': typeof ClassesIdRoute
  '/classes/manage': typeof ClassesManageRoute
  '/parent/billing': typeof ParentBillingRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/tools': typeof StudentToolsRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/availability': typeof TutorAvailabilityRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/get-listed': typeof TutorGetListedRoute
  '/tutor/growth': typeof TutorGrowthRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/profile': typeof TutorProfileRoute
  '/tutor/resources': typeof TutorResourcesRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRouteWithChildren
  '/tutor/tools': typeof TutorToolsRoute
  '/tutor/wallet': typeof TutorWalletRoute
  '/classes/': typeof ClassesIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/parent/children/$childId': typeof ParentChildrenChildIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/student/classes/$id': typeof StudentClassesIdRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/tutor/lessons/$id': typeof TutorLessonsIdRoute
  '/tutor/lessons/new': typeof TutorLessonsNewRoute
  '/tutor/students/$id': typeof TutorStudentsIdRoute
  '/parent/children/': typeof ParentChildrenIndexRoute
  '/parent/classes/': typeof ParentClassesIndexRoute
  '/student/classes/': typeof StudentClassesIndexRoute
  '/student/lessons/': typeof StudentLessonsIndexRoute
  '/student/tutors/': typeof StudentTutorsIndexRoute
  '/tutor/lessons/': typeof TutorLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/parent'
    | '/privacy'
    | '/signup'
    | '/student'
    | '/terms'
    | '/tutor'
    | '/admin/moderation'
    | '/classes/$id'
    | '/classes/manage'
    | '/parent/billing'
    | '/parent/notifications'
    | '/parent/settings'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/messages'
    | '/student/notifications'
    | '/student/settings'
    | '/student/tools'
    | '/tutor/analytics'
    | '/tutor/availability'
    | '/tutor/calendar'
    | '/tutor/earnings'
    | '/tutor/get-listed'
    | '/tutor/growth'
    | '/tutor/messages'
    | '/tutor/notifications'
    | '/tutor/profile'
    | '/tutor/resources'
    | '/tutor/reviews'
    | '/tutor/sessions'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor/tools'
    | '/tutor/wallet'
    | '/classes/'
    | '/parent/'
    | '/student/'
    | '/tutor/'
    | '/parent/children/$childId'
    | '/parent/classes/$id'
    | '/student/classes/$id'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/tutor/lessons/$id'
    | '/tutor/lessons/new'
    | '/tutor/students/$id'
    | '/parent/children/'
    | '/parent/classes/'
    | '/student/classes/'
    | '/student/lessons/'
    | '/student/tutors/'
    | '/tutor/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/moderation'
    | '/classes/$id'
    | '/classes/manage'
    | '/parent/billing'
    | '/parent/notifications'
    | '/parent/settings'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/messages'
    | '/student/notifications'
    | '/student/settings'
    | '/student/tools'
    | '/tutor/analytics'
    | '/tutor/availability'
    | '/tutor/calendar'
    | '/tutor/earnings'
    | '/tutor/get-listed'
    | '/tutor/growth'
    | '/tutor/messages'
    | '/tutor/notifications'
    | '/tutor/profile'
    | '/tutor/resources'
    | '/tutor/reviews'
    | '/tutor/sessions'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor/tools'
    | '/tutor/wallet'
    | '/classes'
    | '/parent'
    | '/student'
    | '/tutor'
    | '/parent/children/$childId'
    | '/parent/classes/$id'
    | '/student/classes/$id'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/tutor/lessons/$id'
    | '/tutor/lessons/new'
    | '/tutor/students/$id'
    | '/parent/children'
    | '/parent/classes'
    | '/student/classes'
    | '/student/lessons'
    | '/student/tutors'
    | '/tutor/lessons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/parent'
    | '/privacy'
    | '/signup'
    | '/student'
    | '/terms'
    | '/tutor'
    | '/admin/moderation'
    | '/classes/$id'
    | '/classes/manage'
    | '/parent/billing'
    | '/parent/notifications'
    | '/parent/settings'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/messages'
    | '/student/notifications'
    | '/student/settings'
    | '/student/tools'
    | '/tutor/analytics'
    | '/tutor/availability'
    | '/tutor/calendar'
    | '/tutor/earnings'
    | '/tutor/get-listed'
    | '/tutor/growth'
    | '/tutor/messages'
    | '/tutor/notifications'
    | '/tutor/profile'
    | '/tutor/resources'
    | '/tutor/reviews'
    | '/tutor/sessions'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor/tools'
    | '/tutor/wallet'
    | '/classes/'
    | '/parent/'
    | '/student/'
    | '/tutor/'
    | '/parent/children/$childId'
    | '/parent/classes/$id'
    | '/student/classes/$id'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/tutor/lessons/$id'
    | '/tutor/lessons/new'
    | '/tutor/students/$id'
    | '/parent/children/'
    | '/parent/classes/'
    | '/student/classes/'
    | '/student/lessons/'
    | '/student/tutors/'
    | '/tutor/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  TermsRoute: typeof TermsRoute
  TutorRoute: typeof TutorRouteWithChildren
  AdminModerationRoute: typeof AdminModerationRoute
  ClassesIdRoute: typeof ClassesIdRoute
  ClassesManageRoute: typeof ClassesManageRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/wallet': {
      id: '/tutor/wallet'
      path: '/wallet'
      fullPath: '/tutor/wallet'
      preLoaderRoute: typeof TutorWalletRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/tools': {
      id: '/tutor/tools'
      path: '/tools'
      fullPath: '/tutor/tools'
      preLoaderRoute: typeof TutorToolsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/students': {
      id: '/tutor/students'
      path: '/students'
      fullPath: '/tutor/students'
      preLoaderRoute: typeof TutorStudentsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/settings': {
      id: '/tutor/settings'
      path: '/settings'
      fullPath: '/tutor/settings'
      preLoaderRoute: typeof TutorSettingsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/sessions': {
      id: '/tutor/sessions'
      path: '/sessions'
      fullPath: '/tutor/sessions'
      preLoaderRoute: typeof TutorSessionsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/reviews': {
      id: '/tutor/reviews'
      path: '/reviews'
      fullPath: '/tutor/reviews'
      preLoaderRoute: typeof TutorReviewsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/resources': {
      id: '/tutor/resources'
      path: '/resources'
      fullPath: '/tutor/resources'
      preLoaderRoute: typeof TutorResourcesRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/profile': {
      id: '/tutor/profile'
      path: '/profile'
      fullPath: '/tutor/profile'
      preLoaderRoute: typeof TutorProfileRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/notifications': {
      id: '/tutor/notifications'
      path: '/notifications'
      fullPath: '/tutor/notifications'
      preLoaderRoute: typeof TutorNotificationsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/messages': {
      id: '/tutor/messages'
      path: '/messages'
      fullPath: '/tutor/messages'
      preLoaderRoute: typeof TutorMessagesRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/growth': {
      id: '/tutor/growth'
      path: '/growth'
      fullPath: '/tutor/growth'
      preLoaderRoute: typeof TutorGrowthRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/get-listed': {
      id: '/tutor/get-listed'
      path: '/get-listed'
      fullPath: '/tutor/get-listed'
      preLoaderRoute: typeof TutorGetListedRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/earnings': {
      id: '/tutor/earnings'
      path: '/earnings'
      fullPath: '/tutor/earnings'
      preLoaderRoute: typeof TutorEarningsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/calendar': {
      id: '/tutor/calendar'
      path: '/calendar'
      fullPath: '/tutor/calendar'
      preLoaderRoute: typeof TutorCalendarRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/availability': {
      id: '/tutor/availability'
      path: '/availability'
      fullPath: '/tutor/availability'
      preLoaderRoute: typeof TutorAvailabilityRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/analytics': {
      id: '/tutor/analytics'
      path: '/analytics'
      fullPath: '/tutor/analytics'
      preLoaderRoute: typeof TutorAnalyticsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/student/tools': {
      id: '/student/tools'
      path: '/tools'
      fullPath: '/student/tools'
      preLoaderRoute: typeof StudentToolsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/bookings': {
      id: '/student/bookings'
      path: '/bookings'
      fullPath: '/student/bookings'
      preLoaderRoute: typeof StudentBookingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/billing': {
      id: '/parent/billing'
      path: '/billing'
      fullPath: '/parent/billing'
      preLoaderRoute: typeof ParentBillingRouteImport
      parentRoute: typeof ParentRoute
    }
    '/classes/manage': {
      id: '/classes/manage'
      path: '/classes/manage'
      fullPath: '/classes/manage'
      preLoaderRoute: typeof ClassesManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$id': {
      id: '/classes/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/lessons/': {
      id: '/tutor/lessons/'
      path: '/lessons'
      fullPath: '/tutor/lessons/'
      preLoaderRoute: typeof TutorLessonsIndexRouteImport
      parentRoute: typeof TutorRoute
    }
    '/student/tutors/': {
      id: '/student/tutors/'
      path: '/tutors'
      fullPath: '/student/tutors/'
      preLoaderRoute: typeof StudentTutorsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons/': {
      id: '/student/lessons/'
      path: '/lessons'
      fullPath: '/student/lessons/'
      preLoaderRoute: typeof StudentLessonsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/classes/': {
      id: '/student/classes/'
      path: '/classes'
      fullPath: '/student/classes/'
      preLoaderRoute: typeof StudentClassesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/classes/': {
      id: '/parent/classes/'
      path: '/classes'
      fullPath: '/parent/classes/'
      preLoaderRoute: typeof ParentClassesIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children/': {
      id: '/parent/children/'
      path: '/children'
      fullPath: '/parent/children/'
      preLoaderRoute: typeof ParentChildrenIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/tutor/students/$id': {
      id: '/tutor/students/$id'
      path: '/$id'
      fullPath: '/tutor/students/$id'
      preLoaderRoute: typeof TutorStudentsIdRouteImport
      parentRoute: typeof TutorStudentsRoute
    }
    '/tutor/lessons/new': {
      id: '/tutor/lessons/new'
      path: '/lessons/new'
      fullPath: '/tutor/lessons/new'
      preLoaderRoute: typeof TutorLessonsNewRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/lessons/$id': {
      id: '/tutor/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/tutor/lessons/$id'
      preLoaderRoute: typeof TutorLessonsIdRouteImport
      parentRoute: typeof TutorRoute
    }
    '/student/tutors/$id': {
      id: '/student/tutors/$id'
      path: '/tutors/$id'
      fullPath: '/student/tutors/$id'
      preLoaderRoute: typeof StudentTutorsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons/$id': {
      id: '/student/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/student/lessons/$id'
      preLoaderRoute: typeof StudentLessonsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/classes/$id': {
      id: '/student/classes/$id'
      path: '/classes/$id'
      fullPath: '/student/classes/$id'
      preLoaderRoute: typeof StudentClassesIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/classes/$id': {
      id: '/parent/classes/$id'
      path: '/classes/$id'
      fullPath: '/parent/classes/$id'
      preLoaderRoute: typeof ParentClassesIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children/$childId': {
      id: '/parent/children/$childId'
      path: '/children/$childId'
      fullPath: '/parent/children/$childId'
      preLoaderRoute: typeof ParentChildrenChildIdRouteImport
      parentRoute: typeof ParentRoute
    }
  }
}

interface ParentRouteChildren {
  ParentBillingRoute: typeof ParentBillingRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentIndexRoute: typeof ParentIndexRoute
  ParentChildrenChildIdRoute: typeof ParentChildrenChildIdRoute
  ParentClassesIdRoute: typeof ParentClassesIdRoute
  ParentChildrenIndexRoute: typeof ParentChildrenIndexRoute
  ParentClassesIndexRoute: typeof ParentClassesIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentBillingRoute: ParentBillingRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentIndexRoute: ParentIndexRoute,
  ParentChildrenChildIdRoute: ParentChildrenChildIdRoute,
  ParentClassesIdRoute: ParentClassesIdRoute,
  ParentChildrenIndexRoute: ParentChildrenIndexRoute,
  ParentClassesIndexRoute: ParentClassesIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentBookingsRoute: typeof StudentBookingsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentToolsRoute: typeof StudentToolsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentClassesIdRoute: typeof StudentClassesIdRoute
  StudentLessonsIdRoute: typeof StudentLessonsIdRoute
  StudentTutorsIdRoute: typeof StudentTutorsIdRoute
  StudentClassesIndexRoute: typeof StudentClassesIndexRoute
  StudentLessonsIndexRoute: typeof StudentLessonsIndexRoute
  StudentTutorsIndexRoute: typeof StudentTutorsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBookingsRoute: StudentBookingsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentToolsRoute: StudentToolsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentClassesIdRoute: StudentClassesIdRoute,
  StudentLessonsIdRoute: StudentLessonsIdRoute,
  StudentTutorsIdRoute: StudentTutorsIdRoute,
  StudentClassesIndexRoute: StudentClassesIndexRoute,
  StudentLessonsIndexRoute: StudentLessonsIndexRoute,
  StudentTutorsIndexRoute: StudentTutorsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TutorStudentsRouteChildren {
  TutorStudentsIdRoute: typeof TutorStudentsIdRoute
}

const TutorStudentsRouteChildren: TutorStudentsRouteChildren = {
  TutorStudentsIdRoute: TutorStudentsIdRoute,
}

const TutorStudentsRouteWithChildren = TutorStudentsRoute._addFileChildren(
  TutorStudentsRouteChildren,
)

interface TutorRouteChildren {
  TutorAnalyticsRoute: typeof TutorAnalyticsRoute
  TutorAvailabilityRoute: typeof TutorAvailabilityRoute
  TutorCalendarRoute: typeof TutorCalendarRoute
  TutorEarningsRoute: typeof TutorEarningsRoute
  TutorGetListedRoute: typeof TutorGetListedRoute
  TutorGrowthRoute: typeof TutorGrowthRoute
  TutorMessagesRoute: typeof TutorMessagesRoute
  TutorNotificationsRoute: typeof TutorNotificationsRoute
  TutorProfileRoute: typeof TutorProfileRoute
  TutorResourcesRoute: typeof TutorResourcesRoute
  TutorReviewsRoute: typeof TutorReviewsRoute
  TutorSessionsRoute: typeof TutorSessionsRoute
  TutorSettingsRoute: typeof TutorSettingsRoute
  TutorStudentsRoute: typeof TutorStudentsRouteWithChildren
  TutorToolsRoute: typeof TutorToolsRoute
  TutorWalletRoute: typeof TutorWalletRoute
  TutorIndexRoute: typeof TutorIndexRoute
  TutorLessonsIdRoute: typeof TutorLessonsIdRoute
  TutorLessonsNewRoute: typeof TutorLessonsNewRoute
  TutorLessonsIndexRoute: typeof TutorLessonsIndexRoute
}

const TutorRouteChildren: TutorRouteChildren = {
  TutorAnalyticsRoute: TutorAnalyticsRoute,
  TutorAvailabilityRoute: TutorAvailabilityRoute,
  TutorCalendarRoute: TutorCalendarRoute,
  TutorEarningsRoute: TutorEarningsRoute,
  TutorGetListedRoute: TutorGetListedRoute,
  TutorGrowthRoute: TutorGrowthRoute,
  TutorMessagesRoute: TutorMessagesRoute,
  TutorNotificationsRoute: TutorNotificationsRoute,
  TutorProfileRoute: TutorProfileRoute,
  TutorResourcesRoute: TutorResourcesRoute,
  TutorReviewsRoute: TutorReviewsRoute,
  TutorSessionsRoute: TutorSessionsRoute,
  TutorSettingsRoute: TutorSettingsRoute,
  TutorStudentsRoute: TutorStudentsRouteWithChildren,
  TutorToolsRoute: TutorToolsRoute,
  TutorWalletRoute: TutorWalletRoute,
  TutorIndexRoute: TutorIndexRoute,
  TutorLessonsIdRoute: TutorLessonsIdRoute,
  TutorLessonsNewRoute: TutorLessonsNewRoute,
  TutorLessonsIndexRoute: TutorLessonsIndexRoute,
}

const TutorRouteWithChildren = TutorRoute._addFileChildren(TutorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  TermsRoute: TermsRoute,
  TutorRoute: TutorRouteWithChildren,
  AdminModerationRoute: AdminModerationRoute,
  ClassesIdRoute: ClassesIdRoute,
  ClassesManageRoute: ClassesManageRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
