/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentCurriculumRouteImport } from './routes/student.curriculum'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentBookingsRouteImport } from './routes/student.bookings'
import { Route as StudentTutorsIndexRouteImport } from './routes/student.tutors.index'
import { Route as StudentLessonsIndexRouteImport } from './routes/student.lessons.index'
import { Route as StudentTutorsIdRouteImport } from './routes/student.tutors.$id'
import { Route as StudentLessonsIdRouteImport } from './routes/student.lessons.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCurriculumRoute = StudentCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBookingsRoute = StudentBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTutorsIndexRoute = StudentTutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsIndexRoute = StudentLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTutorsIdRoute = StudentTutorsIdRouteImport.update({
  id: '/tutors/$id',
  path: '/tutors/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsIdRoute = StudentLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/student/lessons/': typeof StudentLessonsIndexRoute
  '/student/tutors/': typeof StudentTutorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student': typeof StudentIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/student/lessons': typeof StudentLessonsIndexRoute
  '/student/tutors': typeof StudentTutorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/student/bookings': typeof StudentBookingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
  '/student/tutors/$id': typeof StudentTutorsIdRoute
  '/student/lessons/': typeof StudentLessonsIndexRoute
  '/student/tutors/': typeof StudentTutorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/curriculum'
    | '/student/messages'
    | '/student/settings'
    | '/student/'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/student/lessons/'
    | '/student/tutors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/curriculum'
    | '/student/messages'
    | '/student/settings'
    | '/student'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/student/lessons'
    | '/student/tutors'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/student/bookings'
    | '/student/calendar'
    | '/student/curriculum'
    | '/student/messages'
    | '/student/settings'
    | '/student/'
    | '/student/lessons/$id'
    | '/student/tutors/$id'
    | '/student/lessons/'
    | '/student/tutors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/curriculum': {
      id: '/student/curriculum'
      path: '/curriculum'
      fullPath: '/student/curriculum'
      preLoaderRoute: typeof StudentCurriculumRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/bookings': {
      id: '/student/bookings'
      path: '/bookings'
      fullPath: '/student/bookings'
      preLoaderRoute: typeof StudentBookingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tutors/': {
      id: '/student/tutors/'
      path: '/tutors'
      fullPath: '/student/tutors/'
      preLoaderRoute: typeof StudentTutorsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons/': {
      id: '/student/lessons/'
      path: '/lessons'
      fullPath: '/student/lessons/'
      preLoaderRoute: typeof StudentLessonsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tutors/$id': {
      id: '/student/tutors/$id'
      path: '/tutors/$id'
      fullPath: '/student/tutors/$id'
      preLoaderRoute: typeof StudentTutorsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons/$id': {
      id: '/student/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/student/lessons/$id'
      preLoaderRoute: typeof StudentLessonsIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentBookingsRoute: typeof StudentBookingsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCurriculumRoute: typeof StudentCurriculumRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentLessonsIdRoute: typeof StudentLessonsIdRoute
  StudentTutorsIdRoute: typeof StudentTutorsIdRoute
  StudentLessonsIndexRoute: typeof StudentLessonsIndexRoute
  StudentTutorsIndexRoute: typeof StudentTutorsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBookingsRoute: StudentBookingsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCurriculumRoute: StudentCurriculumRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentLessonsIdRoute: StudentLessonsIdRoute,
  StudentTutorsIdRoute: StudentTutorsIdRoute,
  StudentLessonsIndexRoute: StudentLessonsIndexRoute,
  StudentTutorsIndexRoute: StudentTutorsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
